name: my 2nd workflow
on: push
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"
      - name: command
        run: date
      - name: list
        run: ls -la 
      
