name: multi os example
on: push
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu job
        run: echo "hello from linux"
  windows:
    runs-on: windows-2022
    steps:
      - name: windows job 
        run: echo "hello form window"
  mac-os:
    runs-on: macos-13
    steps:
      - name: macos
        run: echo "hello from macos"
